### ISSUE TITLE
tkinter error?

### ISSUE THREAD

**Issue by danindiana** [calcuis/callgg#1]
Traceback (most recent call last):
  File "/home/user/programs/calcuis/chat_gui_env/bin/callgg", line 8, in <module>
    sys.exit(__main__())
  File "/home/user/programs/calcuis/chat_gui_env/lib/python3.8/site-packages/callgg/__main__.py", line 77, in __main__
    from gguf_selector import connector
  File "/home/user/programs/calcuis/chat_gui_env/lib/python3.8/site-packages/gguf_selector/connector.py", line 22, in <module>
    from tkinter import *
ModuleNotFoundError: No module named 'tkinter'

pip install tkinter
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter

pip install tkinter
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter
(chat_gui_env) user@zero-one:~/programs/calcuis$ pip3 install Tk interface
Collecting Tk
  Downloading tk-0.1.0-py3-none-any.whl (3.9 kB)
Collecting interface
  Downloading Interface-2.11.1.tar.gz (19 kB)
Collecting zope.interface
  Downloading zope.interface-6.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (249 kB)
     |████████████████████████████████| 249 kB 11.9 MB/s 
Collecting zope.schema
  Downloading zope.schema-7.0.1-py3-none-any.whl (85 kB)
     |████████████████████████████████| 85 kB 16.8 MB/s 
Requirement already satisfied: setuptools in ./chat_gui_env/lib/python3.8/site-packages (from zope.interface->interface) (44.0.0)
Collecting zope.event
  Downloading zope.event-5.0-py3-none-any.whl (6.8 kB)
Building wheels for collected packages: interface
  Building wheel for interface (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/programs/calcuis/chat_gui_env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2f9g76r1/interface/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2f9g76r1/interface/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3h0pph9b
       cwd: /tmp/pip-install-2f9g76r1/interface/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for interface
  Running setup.py clean for interface
Failed to build interface
Installing collected packages: Tk, zope.interface, zope.event, zope.schema, interface
    Running setup.py install for interface ... done
Successfully installed Tk-0.1.0 interface-2.11.1 zope.event-5.0 zope.interface-6.3 zope.schema-7.0.1

python --version
Python 3.8.10

OS: Ubuntu 20.04 focal
 Kernel: x86_64 Linux 5.15.0-102-generic
 Uptime: 16m
 Packages: 2020
 Shell: bash 5.0.17
 Disk: 98G / 1.9T (6%)
 CPU: AMD Ryzen 9 7950X3D 16-Core @ 32x 4.2GHz
 GPU: AMD/ATI
 RAM: 3093MiB / 192425MiB

**Comment by calcuis** [comment]
python version 3.x comes with tkinter; so you don't need to install it from pip actually; try pip3 instead of pip to install callgg, i.e., pip3 install callgg; then use python3 to run it instead of python since ubuntu or linux or macOS may need to specify python version (python3 means python version 3.x and python refers to python versions 1.x-2.x); just tested callgg in mac and windows recently, it works fine; and your hardware is great definitely; if it doesn't work, try to reinstall/upgrade your python to the latest version

**Comment by calcuis** [comment]
don't bother on installing tkinter; it is the default module (built-in) in python3; this issue will be closed at this point; if the error still welcome to open a new issue
